- src/matrix.zig
Though it is a image processing library, it is nice to have them at least in near future, I believe.
- Added `sumRows()`, `sumCols()` for dim-wise sum
- Changed `norm` function to a general p-norm one
- Added typical norms including `Frobenius`, `Nuclear`, `Max`, `Min`
> Add various matrix norms

- README.md
- src/colorspace.zig
- src/draw.zig
- src/geometry.zig
- src/image.zig
- src/matrix.zig
This commit addresses the initial phase of a comprehensive code review, focusing primarily on documentation improvements, typo corrections, and minor code clarifications across several modules.
Key changes include:
- README.md:
- Corrected a typo in the installation instructions.
- Expanded the features list for drawing functions.
- src/colorspace.zig:
- Removed an unused function (`assertAllFieldTypesAreSame`).
- Corrected u8 (grayscale) conversion logic for Lms, Oklab, and Xyb.
- Enhanced documentation for clarity, especially for the `convert` function's u8 input assumptions and added a file-level comment.
- Fixed a typo in a test name.
- src/draw.zig:
- Added/expanded doc comments for all public functions with detailed parameter explanations.
- Added inline comments to complex …
> Refactor: Comprehensive code review and documentation overhaul

- src/canvas.zig
- src/image.zig
Implement SIMD-optimized path for 4-channel u8 structs like RGBA, this gives a 2x speedup.
> perf(image): optimize integral image for RGBA

- build.zig
- examples/build.zig
- examples/src/colorspaces.zig
- examples/src/png_example.zig
- examples/web/colorspaces.html
- examples/web/colorspaces.js
- src/canvas.zig
- src/color.zig
- src/color/conversions.zig
- src/deflate.zig
- src/image.zig
- src/png.zig
- src/root.zig
- Implements a pure Zig PNG codec with full deflate compression/decompression
- Refactors the examples build system for better organization and usability
- **New `png.zig`**: Complete PNG encoder/decoder supporting RGB, RGBA, grayscale
- **New `deflate.zig`**: Pure Zig deflate compression/decompression (RFC 1951)
- **Automatic color space conversion**: Any format ↔ any format with optimized paths
- **Zero external dependencies**: No libpng requirements
- **Separated concerns**: `wasm_modules` vs `exec_examples` arrays
- **Individual run steps**: `run-{example-name}` for each executable example
- **Unified run-all**: `run-all` to execute all examples at once
- **Added PNG/deflate tests** to main library test suite
- **Cross-platform support**: WASM and native targets maintained
> feat(png): add PNG codec support

- src/geometry/transforms.zig
- src/matrix.zig
Summary
This PR significantly enhances the matrix API by improving the OpsBuilder pattern, updating AffineTransform to use dynamic matrices with proper SMatrix
integration, and consolidating the test suite for better coverage and organization.
Key Changes
🔧 API Improvements
- Renamed exec() → toOwned() in OpsBuilder to better reflect ownership transfer (follows ArrayList convention)
- Renamed methods for clarity: getSubMatrix() → subMatrix(), getCol() → col()
- Added row() method to both SMatrix and OpsBuilder for symmetric row/column extraction
- Added conversion methods: SMatrix.toMatrix() and enhanced Matrix conversion capabilities
⚡ Enhanced OpsBuilder
- Moved matrix operations to OpsBuilder: inverse(), subMatrix(), col(), row()
- Removed redundant methods from Matrix(T) - operations …
> refactor(matrix): enhance OpsBuilder API and improve AffineTransform integration

- examples/src/colorspaces.zig
- examples/web/colorspaces.html
- examples/web/colorspaces.js
- src/color.zig
- src/color/Hsl.zig
- src/color/Hsv.zig
- src/color/Lab.zig
- src/color/Lms.zig
- src/color/Oklab.zig
- src/color/Oklch.zig
- src/color/Rgb.zig
- src/color/Rgba.zig
- src/color/Xyb.zig
- src/color/Xyz.zig
- src/color/Ycbcr.zig
- src/color/conversions.zig
- src/color/formatting.zig
- src/image.zig
- src/matrix/Matrix.zig
- src/matrix/SMatrix.zig
- src/matrix/formatting.zig
- src/root.zig
Implement Oklch color space with conversions to and from all
existing color spaces. Update color conversion examples and web
demo to include Oklch. Refine `writer` type annotations in
formatting functions.
> feat(colorspaces): add Oklch color space

- examples/src/colorspaces.zig
- examples/web/colorspaces.html
- examples/web/colorspaces.js
- src/color.zig
- src/color/Hsl.zig
- src/color/Hsv.zig
- src/color/Lab.zig
- src/color/Lch.zig
- src/color/Lms.zig
- src/color/Oklab.zig
- src/color/Oklch.zig
- src/color/Rgb.zig
- src/color/Rgba.zig
- src/color/Xyb.zig
- src/color/Xyz.zig
- src/color/Ycbcr.zig
- src/color/conversions.zig
- src/root.zig
Introduces the LCh (Lightness, Chroma, Hue) color space with full conversion support to and from all other color spaces. Updates the web example to include LCh for interactive conversions.
> feat(color): add LCh color space and conversions

- bindings/python/scripts/update_version.py
- bindings/python/src/image.zig
- src/sixel.zig
Implement Python's `__format__` method for `ImageRgb` objects, allowing formatted string representation for display using specifiers like 'ansi', 'sixel', and 'auto'.
> feat(python): add `__format__` method for display

- examples/src/face_alignment.zig
- src/image.zig
- src/image/image.zig
- src/image/tests/interpolation.zig
Added the following methods
| Method      | Quality | Speed | Best Use Case       | Overshoot |
|-------------|---------|-------|---------------------|-----------|
| Nearest     | ★☆☆☆☆   | ★★★★★ | Pixel art, masks    | No        |
| Bilinear    | ★★☆☆☆   | ★★★★☆ | Real-time, preview  | No        |
| Bicubic     | ★★★☆☆   | ★★★☆☆ | General purpose     | Yes       |
| Catmull-Rom | ★★★★☆   | ★★★☆☆ | Natural images      | No        |
| Lanczos3    | ★★★★★   | ★★☆☆☆ | High-quality resize | Yes       |
| Mitchell    | ★★★★☆   | ★★☆☆☆ | Balanced quality    | Yes       |
> feat(image): add image interpolation methods

- bindings/python/pyproject.toml
- bindings/python/src/generate_stubs.zig
Moves test and docs dependencies into uv's dev-dependencies. Removes the redundant 'zignal.pyi' stub file.
Adjusts Ruff line length to 99 characters.
> chore(python): consolidate dev dependencies and stub generation

- src/font/BitmapFont.zig
- src/font/bdf.zig
Implement the ability to save BitmapFont instances to BDF files. This includes:
- Adding a `save` method to `BitmapFont`.
- Preserving the original font ascent for accurate round-tripping.
- Adding a comprehensive test for BDF save and load roundtrip.
> feat(font): add bdf font saving

- bindings/python/src/image.zig
- src/image.zig
- src/image/Image.zig
- src/image/tests/resize.zig
Introduces a new `scale` method to the `Image` struct, allowing images to be scaled by a given factor.
Refactors the Python `image_scale` binding to leverage this new method, simplifying the implementation and improving error propagation. Renames the `letterbox` test file to `resize` and adds comprehensive tests for the new `scale` functionality.
> feat(image): add image scaling method

- bindings/python/src/convex_hull.zig
- bindings/python/src/generate_stubs.zig
- bindings/python/src/main.zig
- bindings/python/src/py_utils.zig
- bindings/python/tests/test_convex_hull.py
Introduces a `ConvexHull` class to the Python bindings, allowing computation of the convex hull of 2D points using Graham's scan.
> feat(python): add convex hull computation

- bindings/python/pyproject.toml
- bindings/python/scripts/build_docs.py
Refactor the documentation build script to use an 'empty' module for pdoc's search index generation. This enables pdoc to naturally create 'index.html' as the module listing and 'zignal.html' as the main documentation page. Update pyproject.toml to point to the new primary documentation URL.
> chore(python-docs): improve docs build and URL

- .github/workflows/python.yml
- bindings/python/src/image.zig
- examples/src/face_alignment.zig
- src/image/Image.zig
- src/image/tests/transforms.zig
The `Image.rotate` function now accepts an `InterpolationMethod` parameter and implicitly rotates around the image's center, automatically sizing the output. The `Image.rotateAround` function has been removed. Optimized paths for orthogonal rotations were updated. Adds Python bindings for the new `Image.rotate` method. Updates the face alignment example to use the new API and improve cropping.
BREAKING CHANGE: The `Image.rotate` function signature changed to include `InterpolationMethod`. The `Image.rotateAround` function has been removed.
> feat(image): add image rotation with interpolation

- bindings/python/src/image.zig
- bindings/python/tests/test_image.py
Implement a deep copy method for Image objects.
The returned image has independent memory.
> feat(python): add Image.copy method

- bindings/python/src/rectangle.zig
- bindings/python/tests/test_rectangle.py
- src/geometry/Rectangle.zig
- src/image/Image.zig
- src/image/PixelIterator.zig
- src/image/tests/resize.zig
- src/image/tests/transforms.zig
The `right` and `bottom` coordinates of a `Rectangle` are now exclusive. This aligns with common graphics APIs and Python slicing conventions.
This affects `width`, `height`, `contains`, `isEmpty`, and `intersect` methods. Image `getRectangle` and `view` methods also reflect this change.
BREAKING CHANGE: Rectangle's right and bottom coordinates are now exclusive. This means points on the right/bottom edge are no longer considered inside, and width/height calculations no longer include a '+1' for integer types. Rectangles where left == right or top == bottom are now considered empty.
> refactor(rectangle)!: make bounds exclusive

- bindings/python/src/color.zig
- bindings/python/src/color_factory.zig
- bindings/python/tests/test_colors.py
The comparison is always done in the RGBA colorspace, so as long as two colors represent the same visual color, it will return True.
> feat(python): implement comparison for color types

- bindings/python/src/bitmap_font.zig
- bindings/python/src/image.zig
- bindings/python/src/py_utils.zig
- verbose error message with a file/directory path
- removed the second `FileNotFound` switch case, as I though it is redundant. If it was on purpose, or any other reasons to leave it as it is, I will bring back.
I used a `256` sized buffer but shouldn't we allocate it in heap? The file/directory path can be arbitrary long.
> feature(python): add a file path for verbose error msg

- src/canvas.zig
- src/color.zig
- src/color/Hsl.zig
- src/color/Hsv.zig
- src/color/Lab.zig
- src/color/Lch.zig
- src/color/Lms.zig
- src/color/Oklab.zig
- src/color/Oklch.zig
- src/color/Rgb.zig
- src/color/Rgba.zig
- src/color/Xyb.zig
- src/color/Ycbcr.zig
- src/color/blending.zig
- src/root.zig
Refactors color blending logic into a new module (color/blending.zig). Color type .blend() methods now return a new color and require a BlendMode argument, instead of modifying in-place.
BREAKING CHANGE: .blend() methods on color types are no longer in-place and require a BlendMode. Update calls to 'color = color.blend(overlay, .normal)'.
> feat(color)!: add advanced blending modes

- bindings/python/src/canvas.zig
- bindings/python/src/color_factory.zig
- bindings/python/src/color_utils.zig
- bindings/python/src/image.zig
Replaces `parseColorToRgba` with a new generic `parseColorTo` function that can parse Python color objects directly into `u8` (grayscale), `Rgb`, or `Rgba` Zig types.
This improves flexibility and simplifies color handling, especially in image initialization where colors can now be parsed directly into the image's native format.
> refactor(python): generalize color parsing utility

- bindings/python/src/color_factory.zig
- bindings/python/src/color_registry.zig
- bindings/python/src/color_utils.zig
Remove redundant field_names from color binding structs and the unused isSupportedColor function. Introduce a new helper for cleaner color attribute extraction in RGB/RGBA parsing. Update validation ranges for Lab, XYZ, LMS, and XYB color types to improve accuracy.
> refactor(python): streamline color bindings and validation

- bindings/python/MANIFEST.in
- bindings/python/pyproject.toml
- bindings/python/setup.py
Adds .pyi files and py.typed marker to the Python package distribution, enabling static type checking for users.
Updates MANIFEST.in, setup.py, and pyproject.toml for proper inclusion and installation. Also bumps the development version and adds build dependencies.
> build(python): include type stubs

- bindings/python/src/image.zig
- bindings/python/src/main.zig
- bindings/python/src/pixel_proxy.zig
- bindings/python/tests/test_image.py
This now works:
```python
import zignal
image = zignal.Image.load("../../assets/liza.jpg")
image[0, 0]
image[0, 0].r = 0
image[0, 0]
```
before the assignment would not modify the image inplace, but create a copy!
> feat(python): enable direct pixel component assignment

- bindings/python/src/color_factory.zig
- bindings/python/src/image.zig
- bindings/python/src/pixel_proxy.zig
- bindings/python/tests/test_image.py
- src/meta.zig
Implement `__format__`, `to_gray`, `blend`, and various `to_<color_type>` methods for pixel proxy objects. This allows direct color operations and conversions on individual pixels.
> feat(pixel-proxy): add color conversion and blend methods

- bindings/python/src/image.zig
- bindings/python/src/image/core.zig
- bindings/python/src/image/filtering.zig
- bindings/python/src/image/numpy_interop.zig
- bindings/python/src/image/transforms.zig
- bindings/python/src/py_utils.zig
Moves image functionality into dedicated sub-modules for better organization: `core`, `numpy_interop`, `transforms`, and `filtering`.
Updates `py_utils.zig` for integer rectangle parsing and fixes an example in `image_init` docstring.
> refactor(image): split module into sub-modules

- bindings/python/src/image.zig
- bindings/python/src/image/core.zig
- bindings/python/tests/test_image.py
Introduces `Image.set_border` to fill pixels outside a specified rectangle with a given color or default zero.
> feat(image): add set_border method

- bindings/python/src/image/core.zig
- bindings/python/tests/test_image.py
- src/canvas/Canvas.zig
- src/image.zig
If the rectangle and the image don't overlap, everything is a border.
Refactors image operations in `src/image.zig` and `bindings/python/src/image/core.zig` to use `inline else` and `@TypeOf(img.data[0])`.
> fix(image): correct behavior of setBorder

- bindings/python/src/image.zig
- bindings/python/src/image/filtering.zig
- bindings/python/tests/test_image.py
- src/image/ShenCastan.zig
- src/image/filtering.zig
- src/image/tests/shen_castan.zig
Exposes the Shen-Castan edge detection algorithm to Python.
This involved a significant refactor of the underlying Zig ShenCastan configuration struct. Nested thresholding and thinning options were removed, simplifying its API. Parameters like `highRatio`, `lowRel`, `windowSize` are now direct fields (`high_ratio`, `low_rel`, `window_size`), and `use_nms` has been added. These are directly exposed in the Python binding.
Updates Zig tests and adds comprehensive Python tests.
BREAKING CHANGE: The 'ShenCastan' struct in 'src/image/ShenCastan.zig' has been refactored. The 'thresholds' union and 'thin' enum fields have been removed. Direct users of the Zig 'ShenCastan' struct will need to update their code to use the new direct fields: 'smooth', 'window_size', 'high_ratio', 'low_rel', …
> feat(python): add Shen-Castan edge detection

- examples/build.zig
- src/color.zig
- src/color/Ycbcr.zig
- src/color/conversions.zig
- src/image.zig
- src/jpeg.zig
Implements a complete baseline JPEG encoder with decoder improvements, adding ~950 lines of highly optimized encoding capabilities to complement the existing decoder.
- New JPEG encoder - Full baseline DCT encoding (SOF0, 8-bit, Huffman)
- YCbCr subsampling - Support for 4:4:4, 4:2:2, and 4:2:0 chroma subsampling
- Optimized DCT - Replaced AAN with libjpeg's LLM algorithm (12 muls vs 4096 for naive)
- Fixed-point arithmetic - All YCbCr conversions and DCT use integer math for speed
- Convenient API - Simple jpeg.save() function with quality and subsampling options
- Fixed-point YCbCr conversions (16-bit precision, no floats)
- Reciprocal-based quantization (multiply instead of divide)
- Folded DCT normalization into quantization tables
- Achieved PSNR > 40 dB for all subsampling modes …
> feat(jpeg): add baseline JPEG encoder with optimized DCT

- bindings/python/src/bitmap_font.zig
- bindings/python/src/canvas.zig
- bindings/python/src/convex_hull.zig
- bindings/python/src/fdm.zig
- bindings/python/src/image.zig
- bindings/python/src/image/core.zig
- bindings/python/src/image/filtering.zig
- bindings/python/src/image/numpy_interop.zig
- bindings/python/src/image/transforms.zig
- bindings/python/src/matrix.zig
- bindings/python/src/motion_blur.zig
- bindings/python/src/optimization.zig
- bindings/python/src/pca.zig
- bindings/python/src/py_utils.zig
- bindings/python/src/rectangle.zig
- bindings/python/src/transforms.zig
- bindings/python/tests/test_image.py
Uses generic helpers (`genericNew`, `genericDealloc`, `buildTypeObject`) and specialized error functions (`setTypeError`, `setMemoryError`) to reduce boilerplate across all Python binding modules.
> refactor(python): standardize object lifecycle and error handling

- bindings/python/src/image.zig
- bindings/python/src/image/core.zig
- bindings/python/tests/test_image.py
- src/image.zig
Adds the SSIM metric for comparing two images, using the standard 11x11 Gaussian window (sigma=1.5).
This metric is more perceptually meaningful than PSNR and supports grayscale and color images (via Rec. 709 luminance conversion).
> feat(image): implement structural similarity index (ssim)
